version: '3.8'

services:
  # Backend Spring Boot
  backend:
    build:
      context: ./core
      dockerfile: Dockerfile
    container_name: dental-sync-backend
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      # Configurações do banco MySQL
      - SPRING_DATASOURCE_URL=jdbc:mysql://database:3306/dentalsyncdb?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC&characterEncoding=utf8&useUnicode=true
      - SPRING_DATASOURCE_USERNAME=dentalsync
      - SPRING_DATASOURCE_PASSWORD=dental123!@#
      - SPRING_DATASOURCE_DRIVER_CLASS_NAME=com.mysql.cj.jdbc.Driver
      - SPRING_JPA_DATABASE_PLATFORM=org.hibernate.dialect.MySQLDialect
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - SPRING_JPA_SHOW_SQL=false
      # Email (usar variáveis de ambiente na AWS)
      - EMAIL_USERNAME=${EMAIL_USERNAME:-}
      - EMAIL_PASSWORD=${EMAIL_PASSWORD:-}
      # Frontend URL
      - FRONTEND_URL=http://frontend
      # N8N Configuration
      - N8N_WEBHOOK_BASE_URL=http://n8n:5678
      - N8N_WEBHOOK_ENDPOINT=/webhook/dental-sync
    depends_on:
      database:
        condition: service_healthy
    networks:
      - dental-sync-network
    # Limites para AWS free tier
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
        reservations:
          cpus: '0.25'
          memory: 256M
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

  # Frontend React/Nginx
  frontend:
    build:
      context: ./front
      dockerfile: Dockerfile
    container_name: dental-sync-frontend
    restart: unless-stopped
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - dental-sync-network
    # Limites para AWS free tier
    deploy:
      resources:
        limits:
          cpus: '0.2'
          memory: 128M
        reservations:
          cpus: '0.1'
          memory: 64M

  # Banco de dados MySQL
  database:
    image: mysql:8.0-oracle
    container_name: dental-sync-database
    restart: unless-stopped
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root123!@#
      - MYSQL_DATABASE=dentalsyncdb
      - MYSQL_USER=dentalsync
      - MYSQL_PASSWORD=dental123!@#
      - MYSQL_CHARACTER_SET_SERVER=utf8mb4
      - MYSQL_COLLATION_SERVER=utf8mb4_unicode_ci
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init-db.sql:/docker-entrypoint-initdb.d/init-db.sql:ro
    networks:
      - dental-sync-network
    # Configurações otimizadas para low memory
    command: >
      --default-authentication-plugin=mysql_native_password
      --innodb-buffer-pool-size=128M
      --innodb-log-file-size=32M
      --innodb-flush-log-at-trx-commit=2
      --innodb-file-per-table=1
      --max-connections=50
      --thread-cache-size=4
      --query-cache-size=32M
      --tmp-table-size=32M
      --max-heap-table-size=32M
    # Limites para AWS free tier
    deploy:
      resources:
        limits:
          cpus: '0.3'
          memory: 256M
        reservations:
          cpus: '0.15'
          memory: 128M
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "dentalsync", "-pdental123!@#"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

  # N8N para automação
  n8n:
    image: n8nio/n8n:latest
    container_name: dental-sync-n8n
    restart: unless-stopped
    ports:
      - "8888:5678"
    environment:
      - N8N_BASIC_AUTH_ACTIVE=true
      - N8N_BASIC_AUTH_USER=admin
      - N8N_BASIC_AUTH_PASSWORD=admin123!@#
      - N8N_HOST=n8n
      - N8N_PORT=5678
      - N8N_PROTOCOL=http
      - WEBHOOK_URL=http://n8n:5678
      - N8N_ENCRYPTION_KEY=dentalsync2024key
      - DB_TYPE=sqlite
      - N8N_USER_FOLDER=/home/node/.n8n
      - N8N_LOG_LEVEL=info
      - EXECUTIONS_MODE=regular
      - EXECUTIONS_DATA_SAVE_ON_ERROR=all
      - EXECUTIONS_DATA_SAVE_ON_SUCCESS=all
      - EXECUTIONS_DATA_SAVE_MANUAL_EXECUTIONS=true
    volumes:
      - n8n_data:/home/node/.n8n
      - ./n8n/workflows:/home/node/.n8n/workflows
    networks:
      - dental-sync-network
    # Limites para AWS free tier
    deploy:
      resources:
        limits:
          cpus: '0.2'
          memory: 256M
        reservations:
          cpus: '0.1'
          memory: 128M

volumes:
  mysql_data:
    driver: local
  n8n_data:
    driver: local

networks:
  dental-sync-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16 