version: '3.8'

services:
  frontend:
    build:
      context: ./front
      dockerfile: Dockerfile
    container_name: dental-sync-frontend
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx-ssl.conf:/etc/nginx/conf.d/default.conf
      - /etc/letsencrypt:/etc/letsencrypt
      - /var/www/certbot:/var/www/certbot
    depends_on:
      - app
    networks:
      - dental-sync-network
    restart: unless-stopped

  app:
    build:
      context: ./core
      dockerfile: Dockerfile
    container_name: dental-sync-app
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/dentalsync?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      - SPRING_DATASOURCE_USERNAME=${DB_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${DB_PASSWORD}
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - SPRING_JPA_SHOW_SQL=true
      - SPRING_JPA_DATABASE_PLATFORM=org.hibernate.dialect.MySQLDialect
      - FRONTEND_URL=https://dentalsyncbr.com.br
      - SESSION_COOKIE_SECURE=true
      - EMAIL_USERNAME=${EMAIL_USERNAME:-}
      - EMAIL_PASSWORD=${EMAIL_PASSWORD:-}
      - DENTALSYNC_MAIL_FROM=${DENTALSYNC_MAIL_FROM:-noreply@dentalsync.com}
      - DENTALSYNC_MAIL_FROM_NAME=${DENTALSYNC_MAIL_FROM_NAME:-DentalSync Security}
      - DENTALSYNC_2FA_TRUSTED_DEVICE_DURATION_MINUTES=${DENTALSYNC_2FA_TRUSTED_DEVICE_DURATION_MINUTES:-10080}
      - N8N_WEBHOOK_BASE_URL=${N8N_WEBHOOK_BASE_URL:-http://3.21.159.221:8888}
      - N8N_WEBHOOK_ENDPOINT=${N8N_WEBHOOK_ENDPOINT:-/webhook/dental-sync}
      - N8N_INSTANCE_IP=${N8N_INSTANCE_IP:-172.31.13.89}

    depends_on:
      - db
    networks:
      - dental-sync-network
    restart: unless-stopped

  db:
    image: mysql:8.0
    container_name: dental-sync-db
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
      - MYSQL_DATABASE=dentalsync
      - MYSQL_USER=${DB_USERNAME}
      - MYSQL_PASSWORD=${DB_PASSWORD}
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - dental-sync-network
    restart: unless-stopped
    command: --bind-address=0.0.0.0 --default-authentication-plugin=mysql_native_password

volumes:
  mysql_data:

networks:
  dental-sync-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16 