services:
  app:
    build:
      context: .
      dockerfile: core/Dockerfile
    container_name: dental-sync-app
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/dentalsync
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - SPRING_JPA_SHOW_SQL=true
    depends_on:
      - db
    volumes:
      - ./core:/app
    networks:
      - dental-sync-network

  db:
    image: postgres:16-alpine
    container_name: dental-sync-db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=dentalsync
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - dental-sync-network

volumes:
  postgres_data:

networks:
  dental-sync-network:
    driver: bridge 